# Site settings
title: Lost Robot
email: xpander@adam.com.au
description: "Get blogging like it's 1985 with this Commodore 64 theme for Jekyll, the simple, blog aware, static site generator from GitHub."
baseurl: "/c64jekyll/" # the subpath of your site, e.g. /blog/
url: "http://beebul.github.io" # the base hostname & protocol for your site
# twitter_username: regmtait
# github_username:  regmtait

# Build settings
markdown: kramdown
